### PR TITLE
"There is Some Changes in Curicullum file, I change the location of i…

### PR DESCRIPTION
**Pull request by rohityo**
…move info.md file in main curricullum files from details.

### CODE REVIEW

**Comment by abhishekgupta92** [comment]
Have you changed the corresponding galileo code to read the info.md from a
dfiferent location?

Abhishek Gupta <https://medium.com/@abhishekgupta92>
CEO & Co-founder
Read about us at Forbes India 30u30
<https://www.forbesindia.com/article/30-under-30-2020/navgurukul-cracking-the-code-to-success/57717/1>
, TOI
<https://timesofindia.indiatimes.com/home/sunday-times/these-school-dropouts-have-cracked-the-code-to-a-better-life/articleshow/71458732.cms>
or ZDNet
<http://www.zdnet.com/article/this-home-for-underprivileged-coders-will-put-the-indian-government-and-the-it-industry-to-shame/>
or
follow our blog <http://medium.com/navgurukul> for regular updates.
You can contribute now using navgurukul.org/donate. Each rupee matters.

**Comment by rohityo** [comment]
No bhaiya, I only changed in Curicullum files(newton).

**Comment by abhishekgupta92** [comment]
But the issue was to work on Galileo code

**Comment by rohityo** [comment]
As we talked with prahlad so he tell us. you also can changes in newton curriculum files.

**Comment by rohityo** [comment]
yeah, I have some changed in galileo repo where the files is related from seed-courses.

**Comment by abhishekgupta92** [comment]
Seed-courses scripts change karni hai!

**Pull request merged**
